# Используем базовый образ MongoDB
FROM mongo

# Установим переменные среды для MongoDB (необязательно, если будем использовать .env файл)
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password
ENV MONGO_INITDB_DATABASE=medmate

# Копируем файл инициализации для запуска при старте контейнера
COPY init-mongo.js /docker-entrypoint-initdb.d/
